openapi: '3.0.0'

info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT

paths:
  /api/v1/sign-up:
    post:
      summary: sign up end point
      operationId: sign-up
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"



  /api/v1/sign-in:
    post:
      summary: sign up end point
      operationId: sign-in
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /api/v1/confirm-access-code:
    post:
      summary: confirmAccessCode
      operationId: confirm-access-code
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /api/v1/check-email:
    post:
      summary: checkEmail
      operationId: check-email
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /api/v1/get-access-code:
    post:
      summary: checkEmail
      operationId: get-access-code
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /api/v1/verification:
    get:
      summary: checkEmail
      operationId: verification
      security:
        - OAuth2: [read, write, profile]
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /api/v1/get-units:
    get:
      summary: checkEmail
      operationId: get-units
      security:
        - OAuth2: [read, write, profile]
        - TenantSecurity: []
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /api/v1/get-unit-categories-full:
    get:
      summary: checkEmail
      operationId: get-unit-categories-full
      security:
        - OAuth2: [read, write, profile]
        - TenantSecurity: []
      tags:
        - sign up
        - registration
      parameters:
        - name: signUpObject
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer

      responses:
        '200':
          description: An paged array of pets
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        '400':
          description:

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"


components:
  securitySchemes:
    TenantSecurity:
      type: apiKey
      in: header
      name: X-TENANT-ID

    OAuth2:
      type: oauth2
      description: See https://developers.getbase.com/docs/rest/articles/oauth2/requests
      flows:
        password:
          tokenUrl:  http://localhost:8080/auth/realms/master/protocol/openid-connect/token
          scopes:
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only

  schemas:
    Pet:
      type: object
      properties:
        result:
          type: string
