openapi: '3.0.0'

info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT

paths:
  /api/v1/sign-up:
      post:
        summary: sign up end point
        operationId: sign-up
        tags:
          - sign up
          - registration
        parameters:
          - name: signUpObject
            in: query
            description: How many items to return at one time (max 100)
            required: false
            schema:
              type: integer

        responses:
          '200':
            description: An paged array of pets
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Pet"
          '400':
            description:

          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Pet"



  /api/v1/sign-in:
        post:
          summary: sign up end point
          operationId: sign-in
          tags:
            - sign up
            - registration
          parameters:
            - name: signUpObject
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer

          responses:
            '200':
              description: An paged array of pets
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
            '400':
              description:

            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
  /api/v1/confirm-access-code:
        post:
          summary: confirmAccessCode
          operationId: confirm-access-code
          tags:
            - sign up
            - registration
          parameters:
            - name: signUpObject
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer

          responses:
            '200':
              description: An paged array of pets
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
            '400':
              description:

            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
  /api/v1/check-email:
          post:
            summary: checkEmail
            operationId: check-email
            tags:
              - sign up
              - registration
            parameters:
              - name: signUpObject
                in: query
                description: How many items to return at one time (max 100)
                required: false
                schema:
                  type: integer

            responses:
              '200':
                description: An paged array of pets
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/Pet"
              '400':
                description:

              default:
                description: unexpected error
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/Pet"
  /api/v1/get-access-code:
            post:
              summary: checkEmail
              operationId: get-access-code
              tags:
                - sign up
                - registration
              parameters:
                - name: signUpObject
                  in: query
                  description: How many items to return at one time (max 100)
                  required: false
                  schema:
                    type: integer

              responses:
                '200':
                  description: An paged array of pets
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Pet"
                '400':
                  description:

                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Pet"
  /api/v1/protected/verification:
              post:
                summary: checkEmail
                operationId: verification
                tags:
                  - sign up
                  - registration
                parameters:
                  - name: signUpObject
                    in: query
                    description: How many items to return at one time (max 100)
                    required: false
                    schema:
                      type: integer

                responses:
                  '200':
                    description: An paged array of pets
                    content:
                      application/json:
                        schema:
                          $ref: "#/components/schemas/Pet"
                  '400':
                    description:

                  default:
                    description: unexpected error
                    content:
                      application/json:
                        schema:
                          $ref: "#/components/schemas/Pet"

components:
  schemas:
    Pet:
      type: object
      properties:
        result:
          type: string
    SignUpObject:
      type: object
      properties:
        result:
          type: string